# This workflow will build a goplus project
name: XGo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go/XGo
      uses: goplus/setup-xgo@v1.1.0
      with:
        go-version: "1.24"
        xgo-version: "main"

    - name: SingleFile Mode Test
      run: |
        xgo go -ignore-notated-error -t -s ./...

    - name: XGo Format Test
      run: |
        xgo fmt -t ./...
